### ISSUE TITLE
Beautify JNBs with Markdown text

### ISSUE THREAD

**Issue by SchroederB** [rinikerlab/Ensembler#12]
- [x] BasicPotentials 
- [x] BasicSimulations (@linkerst )
- [x] EDS (@SchroederB)
- [x] ConveyorBelt (@dfhahn )
- [x] FreeEnergy (Gerhard?/ @SchroederB  )
- [x] EnhancedSampling (@linkerst )

**Comment by linkerst** [comment]
I will take over BasicSimulations and EnhancedSampling 
We still have to decide if BasicSimulations will include 2D examples.
