### ISSUE TITLE
Problem with nDim with 2D potentials

### ISSUE THREAD

**Issue by linkerst** [rinikerlab/Ensembler#9]
Using a 2D potential currently creates in error in the ##set dim part of basic_systems. This is due to the sympy representation of potential.nDim.  Fix when sympy variables or corresponding valuesare used.

**Comment by SchroederB** [comment]
I fixed the issue by generating a constants dict for all potential, which is a good solution, as this is needed for the sympy implementation style. And I would like in future to use this more.

see commit: #2

**Comment by SchroederB** [comment]
Please Test Langevine with the 2d Sim :)
